"""initial schema

Revision ID: 0ca41a2f1f8a
Revises: 
Create Date: 2026-08-24 10:36:54.573491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ca41a2f1f8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('gateway_count', sa.Integer(), nullable=False),
    sa.Column('ledger_count', sa.Integer(), nullable=False),
    sa.Column('bank_count', sa.Integer(), nullable=False),
    sa.Column('match_count', sa.Integer(), nullable=False),
    sa.Column('exception_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(length=5000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_transaction_id', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('reference_number', sa.String(length=255), nullable=True),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('narration', sa.String(length=1000), nullable=True),
    sa.Column('fee', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('tax', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'domain_transaction_id', name='uq_source_domain_id')
    )
    op.create_index('ix_order_id', 'transactions', ['order_id'], unique=False)
    op.create_index('ix_reference_number', 'transactions', ['reference_number'], unique=False)
    op.create_index('ix_source_domain_id', 'transactions', ['source', 'domain_transaction_id'], unique=False)
    op.create_index('ix_timestamp', 'transactions', ['timestamp'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('stage', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decision', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_run_id', 'audit_events', ['run_id'], unique=False)
    op.create_index('ix_audit_events_timestamp', 'audit_events', ['timestamp'], unique=False)
    op.create_index('ix_audit_events_transaction_id', 'audit_events', ['transaction_id'], unique=False)
    op.create_table('exceptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=True),
    sa.Column('exception_category', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Numeric(), nullable=False),
    sa.Column('financial_exposure', sa.Numeric(), nullable=False),
    sa.Column('expected_cost', sa.Numeric(), nullable=False),
    sa.Column('explanation', sa.String(length=5000), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_action', sa.String(length=500), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exceptions_run_id', 'exceptions', ['run_id'], unique=False)
    op.create_index('ix_exceptions_status', 'exceptions', ['status'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('match_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Numeric(), nullable=False),
    sa.Column('reason', sa.String(length=5000), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_matches_run_id', 'matches', ['run_id'], unique=False)
    op.create_table('reconciliation_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('processing_status', sa.String(length=255), nullable=False),
    sa.Column('resulting_action', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reconciliation_items_run_id', 'reconciliation_items', ['run_id'], unique=False)
    op.create_index('ix_reconciliation_items_transaction_id', 'reconciliation_items', ['transaction_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=True),
    sa.Column('decision_action', sa.String(length=50), nullable=False),
    sa.Column('deterministic_confidence', sa.Numeric(), nullable=True),
    sa.Column('ml_probability', sa.Numeric(), nullable=True),
    sa.Column('candidate_margin', sa.Numeric(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.String(length=5000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decisions_decision_action', 'decisions', ['decision_action'], unique=False)
    op.create_index('ix_decisions_match_id', 'decisions', ['match_id'], unique=False)
    op.create_index('ix_decisions_run_id', 'decisions', ['run_id'], unique=False)
    op.create_table('exception_transactions',
    sa.Column('exception_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('exception_id', 'transaction_id')
    )
    op.create_index('ix_exception_transactions_exception_id', 'exception_transactions', ['exception_id'], unique=False)
    op.create_index('ix_exception_transactions_transaction_id', 'exception_transactions', ['transaction_id'], unique=False)
    op.create_table('match_transactions',
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('match_id', 'transaction_id')
    )
    op.create_index('ix_match_transactions_match_id', 'match_transactions', ['match_id'], unique=False)
    op.create_index('ix_match_transactions_transaction_id', 'match_transactions', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_match_transactions_transaction_id', table_name='match_transactions')
    op.drop_index('ix_match_transactions_match_id', table_name='match_transactions')
    op.drop_table('match_transactions')
    op.drop_index('ix_exception_transactions_transaction_id', table_name='exception_transactions')
    op.drop_index('ix_exception_transactions_exception_id', table_name='exception_transactions')
    op.drop_table('exception_transactions')
    op.drop_index('ix_decisions_run_id', table_name='decisions')
    op.drop_index('ix_decisions_match_id', table_name='decisions')
    op.drop_index('ix_decisions_decision_action', table_name='decisions')
    op.drop_table('decisions')
    op.drop_index('ix_reconciliation_items_transaction_id', table_name='reconciliation_items')
    op.drop_index('ix_reconciliation_items_run_id', table_name='reconciliation_items')
    op.drop_table('reconciliation_items')
    op.drop_index('ix_matches_run_id', table_name='matches')
    op.drop_table('matches')
    op.drop_index('ix_exceptions_status', table_name='exceptions')
    op.drop_index('ix_exceptions_run_id', table_name='exceptions')
    op.drop_table('exceptions')
    op.drop_index('ix_audit_events_transaction_id', table_name='audit_events')
    op.drop_index('ix_audit_events_timestamp', table_name='audit_events')
    op.drop_index('ix_audit_events_run_id', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_timestamp', table_name='transactions')
    op.drop_index('ix_source_domain_id', table_name='transactions')
    op.drop_index('ix_reference_number', table_name='transactions')
    op.drop_index('ix_order_id', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('reconciliation_runs')
    # ### end Alembic commands ###
